[package]
name = "match-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
clap = { version = "4.2.4", features = ["derive"] }
rand = "0.8.5"
