[package]
name = "oe_client"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.17"
shlex = "1.3.0"
tokio = { version = "1.40.0", features = ["full"] }
rand = "0.9.0-alpha.2"
fefix = { version = "0.7.0", features = ["fix44", "fix42"] }