[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.35.1", features = ["full"] }
config = "0.13.4"
common = { version = "0.1.0", path = "../common" }
serde_json = "1.0.111"
rand = "0.8.5"
itertools = "0.12.0"
